/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.marlen.view;

import co.com.marlen.controller.ReportesController;

/**
 *
 * @author Marlen
 */
public class AppGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppGUI
     */
    
    public static ReportesController controller = new ReportesController();
    
    public AppGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        segundoInforme = new javax.swing.JButton();
        primerInforme = new javax.swing.JButton();
        tercerInforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        segundoInforme.setText("Segundo Informe");
        segundoInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoInformeActionPerformed(evt);
            }
        });

        primerInforme.setText("Primer Informe");
        primerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerInformeActionPerformed(evt);
            }
        });

        tercerInforme.setText("Tercer Informe");
        tercerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(primerInforme)
                .addGap(77, 77, 77)
                .addComponent(segundoInforme)
                .addGap(115, 115, 115)
                .addComponent(tercerInforme)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerInforme)
                    .addComponent(segundoInforme)
                    .addComponent(tercerInforme))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void segundoInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoInformeActionPerformed
        SegundoInforme segundoInforme = new SegundoInforme();
        segundoInforme.setVisible(true);
    }//GEN-LAST:event_segundoInformeActionPerformed

    private void primerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerInformeActionPerformed
        PrimerInforme primerInforme = new PrimerInforme();
        primerInforme.setVisible(true);
    }//GEN-LAST:event_primerInformeActionPerformed

    private void tercerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerInformeActionPerformed
        TercerInforme tercerInforme = new TercerInforme();
        tercerInforme.setVisible(true);
    }//GEN-LAST:event_tercerInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton primerInforme;
    private javax.swing.JButton segundoInforme;
    private javax.swing.JButton tercerInforme;
    // End of variables declaration//GEN-END:variables
}
